version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=bot_db
      - POSTGRES_USER=yana
      - POSTGRES_PASSWORD=yana
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5433:5432"

volumes:
  db: